pub mod builder;
mod decode;
mod encode;
mod structs;
pub mod writer;

use heck::ToSnakeCase;
use pojoc_core::types::{is_primitive, ResolvedTypeRef};
use pojoc_schema::ir::ir_types::{DefaultValue, ResolvedSchema};
use std::collections::{HashMap, HashSet};
use writer::CodeWriter;

pub fn generate(schema: &ResolvedSchema) -> String {
    let mut w = CodeWriter::default();

    w.line("// @generated — do not edit");
    w.line("// generated by pojoc");
    w.blank();
    w.line("pub mod runtime { pub use pojoc::*; }");
    w.line("use runtime::*;");
    w.line("#[allow(unused_imports)]");
    w.line("use serde::{Serialize, Deserialize};");
    w.blank();

    let infected = compute_lifetime_infected(schema);

    emit_imported_submodules(schema, &mut w);

    structs::emit_enums(schema, &mut w);
    structs::emit_structs(schema, &infected, &mut w);
    structs::emit_bitsets(schema, &mut w);
    structs::emit_unions(schema, &mut w);
    decode::emit_decode_functions(schema, &infected, &mut w);
    emit_dispatcher(schema, &infected, &mut w);
    w.blank();
    encode::emit_size_hint(schema, &mut w);
    encode::emit_encode_helpers(schema, &mut w);
    encode::emit_encode_vn_functions(schema, &mut w);

    w.finish()
}

fn emit_dispatcher(schema: &ResolvedSchema, infected: &HashSet<String>, w: &mut CodeWriter) {
    let name = &schema.name_hint;
    let latest = schema.lineage.latest_version;
    let needs_lifetime = infected.contains(name.as_str());

    let decode_sig = if needs_lifetime {
        format!("pub fn decode(buf: &[u8]) -> PojocResult<{name}<'_>> {{")
    } else {
        format!("pub fn decode(buf: &[u8]) -> PojocResult<{name}> {{")
    };
    w.line(&decode_sig);
    w.indent();
    w.line("let mut pos = 0;");
    w.line("let envelope = read_envelope(buf, &mut pos)?;");
    w.line("let payload = envelope.payload;");
    w.line("let mut pos = 0;");
    w.line("match envelope.version {");
    w.indent();
    for vl in &schema.lineage.versions {
        let v = vl.version;
        w.line(&format!("{v} => decode_v{v}(payload, &mut pos),"));
    }
    w.line("v => Err(Error::UnsupportedVersion(v)),");
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!(
        "pub fn encode(buf: &mut Vec<u8>, value: &{name}) {{"
    ));
    w.indent();
    w.line("buf.reserve(size_hint(value));");
    w.line(&format!(
        "let len_pos = write_envelope_header(buf, {latest});"
    ));
    w.line("let payload_start = buf.len();");
    w.line(&format!("encode_v{latest}(buf, value);")); // ← was encode_payload
    w.line("let payload_len = buf.len() - payload_start;");
    w.line("patch_envelope_length(buf, len_pos, payload_len);");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!(
        "pub fn encode_for_version(buf: &mut Vec<u8>, value: &{name}, version: u64) -> PojocResult<()> {{"
    ));
    w.indent();
    w.line("buf.reserve(size_hint(value));");
    w.line("let len_pos = write_envelope_header(buf, version);");
    w.line("let payload_start = buf.len();");
    w.line("match version {");
    w.indent();
    for vl in &schema.lineage.versions {
        let v = vl.version;
        w.line(&format!("{v} => encode_v{v}(buf, value),"));
    }
    w.line("v => return Err(Error::UnsupportedVersion(v)),");
    w.dedent();
    w.line("}");
    w.line("let payload_len = buf.len() - payload_start;");
    w.line("patch_envelope_length(buf, len_pos, payload_len);");
    w.line("Ok(())");
    w.dedent();
    w.line("}");
    w.blank();

    w.line("pub fn supported_versions() -> &'static [u64] {");
    w.indent();
    let versions: Vec<String> = schema
        .lineage
        .versions
        .iter()
        .map(|vl| vl.version.to_string())
        .collect();
    w.line(&format!("&[{}]", versions.join(", ")));
    w.dedent();
    w.line("}");
}

fn emit_default(default: &DefaultValue, schema: &ResolvedSchema) -> String {
    match default {
        DefaultValue::None => "None".to_string(),
        DefaultValue::Bool(b) => b.to_string(),
        DefaultValue::Int(i) => i.to_string(),
        DefaultValue::Float(f) => {
            if f.fract() == 0.0 {
                format!("{f:.1}")
            } else {
                f.to_string()
            }
        }
        DefaultValue::Str(s) => format!("PojocString::const_new({s:?})"),
        DefaultValue::Array(els) => {
            if els.is_empty() {
                "PojocVec::new()".to_string()
            } else {
                let pushes = els
                    .iter()
                    .map(|e| format!("__v.push({});", emit_default(e, schema)))
                    .collect::<Vec<_>>()
                    .join(" ");
                format!("{{ let mut __v = PojocVec::new(); {pushes} __v }}")
            }
        }
        DefaultValue::Repeat(_) => unreachable!(
            "DefaultValue::Repeat should always get expanded into DefaultValue::Array before codegen."
        ),
        DefaultValue::Map(pairs) => {
            if pairs.is_empty() {
                "PojocMap::new()".to_string()
            } else {
                let inserts = pairs
                    .iter()
                    .map(|(k, v)| {
                        format!(
                            "__m.insert({}, {});",
                            emit_default(k, schema),
                            emit_default(v, schema)
                        )
                    })
                    .collect::<Vec<_>>()
                    .join(" ");
                format!("{{ let mut __m = PojocMap::new(); {inserts} __m }}")
            }
        }
        DefaultValue::Struct => "Default::default()".to_string(),
        DefaultValue::FixedBytes(bytes) => {
            if bytes.iter().all(|b| b.is_ascii_graphic() || *b == b' ') {
                let s = std::str::from_utf8(bytes).unwrap();
                format!("*b\"{s}\"")
            } else {
                let inner = bytes
                    .iter()
                    .map(|b| format!("0x{b:02x}u8"))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("[{inner}]")
            }
        }
        DefaultValue::Tuple(elements) => {
            let inner = elements
                .iter()
                .map(|e| emit_default(e, schema))
                .collect::<Vec<_>>()
                .join(", ");
            format!("({inner})")
        }
        DefaultValue::EnumVariant { ty_name, variant } => {
            format!("{ty_name}::{variant}")
        }
        DefaultValue::BitsetLiteral { ty_name, kvs } => {
            if let Some((_, resolved_bitset)) = schema
                .bitsets
                .bitsets
                .iter()
                .filter(|(id, _)| id.name == *ty_name)
                .max_by_key(|(id, _)| id.version)
            {
                let computed_len = (resolved_bitset.variants.len() + 7) / 8;
                let mut default_bytes = vec![0u8; computed_len];
                for (flag_name, flag_val) in kvs {
                    if *flag_val {
                        if let Some(idx) =
                            resolved_bitset.variants.iter().position(|v| v == flag_name)
                        {
                            default_bytes[idx / 8] |= 1 << (idx % 8);
                        }
                    }
                }
                let inner = default_bytes
                    .iter()
                    .map(|b| format!("0x{b:02x}"))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("{ty_name}([{inner}])")
            } else {
                format!("{ty_name}::default()")
            }
        }
    }
}

fn get_latest_versions<K, V>(
    items: &HashMap<K, V>,
    get_key_name: impl Fn(&K) -> String,
    get_version: impl Fn(&K) -> i128,
) -> HashMap<String, (i128, &V)>
where
    K: std::hash::Hash + Eq,
{
    let mut latest = HashMap::new();
    for (id, value) in items {
        let version = get_version(id);
        let name = get_key_name(id);
        let entry = latest.entry(name).or_insert((version, value));
        if version > entry.0 {
            *entry = (version, value);
        }
    }
    latest
}

fn compute_lifetime_infected(schema: &ResolvedSchema) -> HashSet<String> {
    let latest = get_latest_versions(&schema.types.types, |id| id.name.clone(), |id| id.version);

    let mut infected: HashSet<String> = latest
        .iter()
        .filter(|(_, (_, resolved))| resolved.fields.iter().any(|f| f.lazy))
        .map(|(name, _)| name.clone())
        .collect();

    if schema
        .versions
        .last()
        .map(|v| v.fields.iter().any(|f| f.lazy))
        .unwrap_or(false)
    {
        infected.insert(schema.name_hint.clone());
    }

    loop {
        let mut changed = false;
        for (name, (_, resolved)) in &latest {
            if infected.contains(name) {
                continue;
            }
            let newly_infected = resolved.fields.iter().any(|f| {
                field_type_name(&f.ty)
                    .map(|n| infected.contains(n))
                    .unwrap_or(false)
            });
            if newly_infected {
                infected.insert(name.clone());
                changed = true;
            }
        }
        if !changed {
            break;
        }
    }

    infected
}

fn field_type_name(ty: &ResolvedTypeRef) -> Option<&str> {
    match ty {
        ResolvedTypeRef::Scalar(id) if !is_primitive(&id.name) => Some(&id.name),
        ResolvedTypeRef::Array(inner)
        | ResolvedTypeRef::FixedArray(inner, _)
        | ResolvedTypeRef::Optional(inner) => field_type_name(inner),
        _ => None,
    }
}

fn emit_imported_submodules(schema: &ResolvedSchema, w: &mut CodeWriter) {
    let mut aliases: Vec<&String> = schema.imports.keys().collect();
    aliases.sort(); // deterministic output

    for alias in aliases {
        let imported = &schema.imports[alias];
        let module = alias.to_snake_case();
        let body = generate(imported);

        w.line(&format!("pub mod {module} {{"));
        w.indent();
        for line in body.lines() {
            if line.is_empty() {
                w.blank();
            } else {
                w.line(line);
            }
        }
        w.dedent();
        w.line("}");
        w.blank();
    }
}
