mod decode;
mod encode;
mod structs;
pub mod types;
pub mod writer;
pub mod builder;

use pojoc_schema::ir::types::{DefaultValue, ResolvedSchema};
use writer::CodeWriter;

pub fn generate(schema: &ResolvedSchema) -> String {
    let mut w = CodeWriter::default();

    w.line("// @generated — do not edit");
    w.line("// generated by pojoc");
    w.blank();
    w.line("pub use pojoc_runtime::*;");
    w.line("use serde::{Serialize, Deserialize};");
    w.blank();

    structs::emit_structs(schema, &mut w);
    decode::emit_decode_functions(schema, &mut w);
    emit_dispatcher(schema, &mut w);
    w.blank();
    encode::emit_size_hint(schema, &mut w);
    encode::emit_encode_function(schema, &mut w);

    w.finish()
}

fn emit_dispatcher(schema: &ResolvedSchema, w: &mut CodeWriter) {
    let name = &schema.name_hint;

    w.line(&format!("pub fn decode(buf: &[u8]) -> Result<{name}> {{"));
    w.indent();
    w.line("let mut pos = 0;");
    w.line("let envelope = read_envelope(buf, &mut pos)?;");
    w.line("let payload = envelope.payload;");
    w.line("let mut pos = 0;");
    w.line("match envelope.version {");
    w.indent();
    for vl in &schema.lineage.versions {
        let v = vl.version;
        w.line(&format!("{v} => decode_v{v}(payload, &mut pos),"));
    }
    w.line(&"v => Err(Error::UnsupportedVersion(v)),".to_string());
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
    w.blank();

    w.line(&format!("pub fn encode(buf: &mut Vec<u8>, value: &{name}) {{"));
    w.indent();
    w.line("buf.reserve(size_hint(value));");
    w.line(&format!("let len_pos = write_envelope_header(buf, {version});", version = &schema.lineage.latest_version));
    w.line("let payload_start = buf.len();");
    w.line("encode_payload(buf, value);");
    w.line("let payload_len = buf.len() - payload_start;");
    w.line("patch_envelope_length(buf, len_pos, payload_len);");
    w.dedent();
    w.line("}");
}

fn emit_default(default: &DefaultValue) -> String {
    match default {
        DefaultValue::Bool(b)  => b.to_string(),
        DefaultValue::Int(i)   => i.to_string(),
        DefaultValue::Float(f) => {
            // ensure it's a valid Rust float literal
            if f.fract() == 0.0 {
                format!("{f:.1}")
            } else {
                f.to_string()
            }
        }
        DefaultValue::Str(s)   => format!("{s:?}.to_string()"),
        DefaultValue::EmptyArray => "PojocVec::new()".to_string(),
        DefaultValue::Struct   => "Default::default()".to_string(),
    }
}